// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestJob.Contexts;

#nullable disable

namespace TestJob.Migrations
{
    [DbContext(typeof(UserStatisticsContext))]
    partial class UserStatisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestJob.Entyties.RequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Percent")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserStatisticsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserStatisticsId");

                    b.ToTable("RequestStatuses");
                });

            modelBuilder.Entity("TestJob.Entyties.UserStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c68acd4-6461-4cca-a11b-bc58192b4c92"),
                            CountSignIn = 12
                        },
                        new
                        {
                            Id = new Guid("0771e564-238c-4b6e-8b6e-096ddbbd2b91"),
                            CountSignIn = 5
                        },
                        new
                        {
                            Id = new Guid("e390e96f-d2f8-4148-8378-b76739f24082"),
                            CountSignIn = 103
                        },
                        new
                        {
                            Id = new Guid("c6e77341-b5c6-4ec2-817f-73232a981124"),
                            CountSignIn = 7
                        });
                });

            modelBuilder.Entity("TestJob.Entyties.RequestStatus", b =>
                {
                    b.HasOne("TestJob.Entyties.UserStatistics", "UserStatistics")
                        .WithMany("RequestStatuses")
                        .HasForeignKey("UserStatisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStatistics");
                });

            modelBuilder.Entity("TestJob.Entyties.UserStatistics", b =>
                {
                    b.Navigation("RequestStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
